### ISSUE TITLE
Laravel 6.1?

### ISSUE THREAD

**Issue by aibarra11** [prwnr/laravel-streamer#13]
Need to use this with laravel 6.1, not sure if that's being tested. Thanks!

**Comment by prwnr** [comment]
I will try to address that this weekend, test and update composer deps to work with ^6.0

**Comment by prwnr** [comment]
Did some quick research on ^5.6 vs ^6.0. Laravel switched from using Predis as default Redis driver to PhpRedis. I was aware of that as well, predis got abandoned sadly. 
This is actually a time for this package to move away from Predis and start using PhpRedis as well. I will try to update current v1 to work with Laravel 6.0, looks mostly like some tests adjustments cause their InteractsWithRedis trait is forcing phpredis.
Switching to 6.0 will require setting up Laravel app to explicitly use Predis as client.
I will start working as soon as possible on v2 to switch to PhpRedis driver.

**Comment by prwnr** [comment]
@aibarra11 can I ask you to check the https://github.com/prwnr/laravel-streamer/tree/phpredis-and-laravel-6 branch if it works for you with Laravel ^6.0 and let me know if any problems occur before I will release new version? 
Basically I only had to adjust internal redis commands calls, so the external API is unchanged. 

Please note that this branch is dropping Predis package usage and switches like Laravel to PhpRedis pecl extension.

**Comment by aibarra11** [comment]
@prwnr I modified composer.json
````
    "require": {
        "php": "^7.2",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.0",
        "laravel/tinker": "^1.0",
        "ramsey/uuid": "^3.8",
        "rebing/graphql-laravel": "^2.1",
        "spatie/laravel-event-sourcing": "^1.0",
        "prwnr/laravel-streamer":"*"
    },

````

ran composer install (removed composer.lock)

I'm not using the package anywhere in this project yet, just did the composer install and got the following error at the very end:

````
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Prwnr\Streamer\ListenersStack::boot() must be of the type array, null given, called in /var/www/html/vendor/prwnr/laravel-streamer/src/StreamerProvider.php on line 29

  at /var/www/html/vendor/prwnr/laravel-streamer/src/ListenersStack.php:19
    15|
    16|     /**
    17|      * @param  array  $events
    18|      */
  > 19|     public static function boot(array $events): void
    20|     {
    21|         self::$events = $events;
    22|     }
    23|

  Exception trace:

  1   Prwnr\Streamer\ListenersStack::boot()
      /var/www/html/vendor/prwnr/laravel-streamer/src/StreamerProvider.php:29

  2   Prwnr\Streamer\StreamerProvider::register()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:608

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
````

**Comment by prwnr** [comment]
Hmm, that looks odd. I created fresh Laravel app:
```
/var/www/html/blog$ composer require prwnr/laravel-streamer:*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing predis/predis (v1.1.1): Loading from cache
  - Installing prwnr/laravel-streamer (dev-phpredis-and-laravel-6 bd97e2a): Cloning bd97e2acce from cache
predis/predis suggests installing ext-phpiredis (Allows faster serialization and deserialization of the Redis protocol)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: prwnr/laravel-streamer
Package manifest generated successfully.
```
but I will add a small adjustment for that ListenersStack to pick up default value if there's a null.

**Comment by aibarra11** [comment]
@prwnr i removed the requirement from your composer.json for 

````
    "predis/predis": "^1.1"
````

and it installed correctly. it should be noted i have php redis install already via 
````
pecl install redis
````
from https://github.com/phpredis/phpredis/blob/develop/INSTALL.markdown

oddly though, there is no mention of phpredis in my project's composer.json. I'l ltry some things out today and see if everything works as expected

even from laravel's docs:

````
Before using Redis with Laravel, we encourage you to install and use the PhpRedis PHP extension via PECL. The extension is more complex to install but may yield better performance for applications that make heavy use of Redis.
````
from https://laravel.com/docs/6.x/redis

guess it just works without an additional packages?

**Comment by prwnr** [comment]
@aibarra11 
>  i removed the requirement from your composer.json for

this is really odd that removing this package got that listeners stack error fixed for you. I left this package in my composer, because Laravel InteractsWithRedis trait sort of requires it (stupid). Gotta move that package to dev requirements maybe.

> oddly though, there is no mention of phpredis in my project's composer.json. I'l ltry some things out today and see if everything works as expected

Its not going to be there. Its PHP extension. You can see the "code" by checking \Redis class. 
There is no additional packages for this pecl version. Just make sure that its 5.0.2 to have all Streams commands included
