### ISSUE TITLE
PHPRedis - RedisException(code: 0): read error on connection to redis-master:6379

### ISSUE THREAD

**Issue by aibarra11** [prwnr/laravel-streamer#17]
Using laravel 6.1 with phpredis. While listening for streams i will get the following error blowing up my logs

````
[2019-12-08 15:49:43] local.ERROR: read error on connection to redis-master:6379 {"exception":"[object] (RedisException(code: 0): read error on connection to redis-master:6379 at /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:111)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(111): Redis->xread(Array, NULL, 0)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(211): Illuminate\\Redis\\Connections\\Connection->command('xread', Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(451): Illuminate\\Redis\\Connections\\Connection->__call('xread', Array)
#3 /var/www/html/vendor/prwnr/laravel-streamer/src/Stream.php(96): Illuminate\\Redis\\Connections\\PhpRedisConnection->__call('xRead', Array)
#4 /var/www/html/vendor/prwnr/laravel-streamer/src/EventDispatcher/Streamer.php(173): Prwnr\\Streamer\\Stream->await('$', 0)
#5 /var/www/html/vendor/prwnr/laravel-streamer/src/EventDispatcher/Streamer.php(152): Prwnr\\Streamer\\EventDispatcher\\Streamer->listenOn(Object(Prwnr\\Streamer\\Stream), Object(Closure))
#6 /var/www/html/vendor/prwnr/laravel-streamer/src/Commands/ListenCommand.php(89): Prwnr\\Streamer\\EventDispatcher\\Streamer->listen('congregation.es...', Object(Closure))
#7 [internal function]: Prwnr\\Streamer\\Commands\\ListenCommand->handle()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(34): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call(Array)
#14 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /var/www/html/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /var/www/html/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Prwnr\\Streamer\\Commands\\ListenCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
````

i did some digging and found that other people have this error with phpredis. Since i'm using the supervisor method to keep things going, i feel like this is something i can ignore until whoever made phpredis has a fix. One solution i found was

````
ini_set("default_socket_timeout", -1);
````

I wasn't sure where to place this, its currently sitting in 

````
\prwnr\laravel-streamer\src\Stream.php

   public function __construct(string $name)
    {
        $this->name = $name;
        ini_set("default_socket_timeout", -1);
    }

````

what are your thoughts on this? I don't want to set this at the system/php level, just on the stream reading itself, just in case other connections timeout.

thanks!

**Comment by prwnr** [comment]
@aibarra11 well, that's interesting. I never saw this in our environment tho, but at my company we are still using Laravel 5.8 and this package 1.6 version, which is still set to use Predis. 
I found open issue on PHPRedis too: https://github.com/phpredis/phpredis/issues/70 (leaving as reference that the problem is there) - this is quite old issue, wondering if they are going to ever work on it :thinking: last comment: https://github.com/phpredis/phpredis/issues/70#issuecomment-348997806

This is quite of a drawback for using PHPRedis, I wonder if Laravel devs knows about this, as Predis is being deprecated in favour of PHPRedis.

As long as you are using Supervisors the only problem with it is having logs of this error (assuming that listeners are running as group/consumer to acknowledge messages and dont process them again). So for now I would keep with this, not seeing any other solution than the ini_set (which is bad smell).

**Comment by aibarra11** [comment]
Ah ok thanks. it is pretty sad we have to resort to the init_set. Supervisors to the rescue😅

**Comment by stgalkin** [comment]
same thing for laravel 7.6.1.
The error occurs after the time from the config('database.redis.connection.read_timeout') parameter.
`read error on connection to redis:6379`

**Comment by OSTurtle** [comment]
any fixes yet? I have the exact same problem.
(Laravel Framework 8.35.1)

**Comment by prwnr** [comment]
> any fixes yet? I have the exact same problem.
> (Laravel Framework 8.35.1)

as stated above, its not really a problem of my package but the PHPRedis extension. So, there will be no fix on my side. I may look into getting Predis supported again as it got picked up by Laravel, but no ETA here.  

the advice here is to use Supervisor as it will solve this and any other unexpected connection loss and will make sure that listeners are always running will little downtime.

**Comment by OSTurtle** [comment]
Yes, sure. But maybe someone has a workaround for this problem.

**Comment by prwnr** [comment]
> Yes, sure. But maybe someone has a workaround for this problem.

check my latest release, I added a `keep-alive` option to command that should mitigate this connection timeout error and restart listening right away. maybe that will help you
