### ISSUE TITLE
Nasłuchiwanie nowych wpisów w konkretnym strumieniu

### ISSUE THREAD

**Issue by andrzejkupczyk** [prwnr/laravel-streamer#19]
@prwnr , ~~czy wykorzystywanie nazw zdarzeń do nazywania streamów jest intencjonalne?~~
Rzecz w tym, że takie podejście jest dość mylące, bo wpisy i strumienie są traktowane jako jedno i to samo. Tymczasem w konkretny strumień mogą wpadać różne wpisy.

~~Co myślisz o tym, by zmienić implementację w taki sposób, by zdarzenia - oprócz nazwy - posiadały również nazwę strumienia?~~ Odpowiednie zmiany pozwoliłyby nasłuchiwać wszystkich zdarzeń we wskazanym strumieniu zamiast konkretnego zdarzenia. Dzięki temu np. jeden konsument mógłby zbierać różne wpisy i kierować je do odpowiednich handlerów. W tej chwili używanie `laravel-streamer` wymaga w teorii odpalania osobnego workera dla każdego zdarzenia.

```bash
php artisan streamer:listen example.streamer.1
php artisan streamer:listen example.streamer.2
php artisan streamer:listen example.streamer.3
…
php artisan streamer:listen example.streamer.n
```

Być może moje wątpliwości wzbudził fakt, że nazywasz wpisy zdarzeniami. Spodziewałem się, że strumienie traktujesz jako kolejkę :thinking: Grupy byłyby tutaj zatem odpowiednikami kanałów (?) Możliwe, że mam problemy ze zrozumieniem samej koncepcji, więc daj proszę znać co o tym wszystkim myślisz.

**Comment by prwnr** [comment]
Pierwotnie paczka powstała dla użytku wewnętrznego do przesyłu eventów pomiędzy aplikacjami bez ich straty (co działo się przy pub/sub który jest fire&forget). Stąd też takie nazewnictwo. Każda wiadomość do streamu traktowana była jako osobne zdarzenie a druga strona nasłuchiwala na to co ją interesuje. 

Tutaj też dochodzi kwestia tego, że w przyszlości planowane też jest dodanie możliwości odtworzenia danego eventu ze streamu (mam to zaczęte, ale brak ETA) od początku jego istnienia do ostatniego zdarzenia (namiastka ES). Z takiego względu też nie do końca widzę, by jeden stream mógł zawierać w sobie masę różnych zdarzeń, bo odczyt z niego byłby dość problematyczny.

Jeżeli dobrze rozumiem, to "zgrzytem" jest tutaj nazwa interfejsu `Event` który tak naprawdę mógłby być nazwany np. `Message` bo to wiadomość wysyłamy na stream, a czy jest ona eventem czy też czymś innym, mogłoby być określone przez jej typ. W takim przypadku payload mógłby dodatkowo określać nazwę eventów jakie dany stream przyjmuje. Wtedy może sama zmiana nazwy interfejsu byłaby wystarczającym na tę chwilę wyjaśnieniem (choć to by wymagało wydania wersji 3 bo zmiana nie byłaby kompatybilna, czego dla samej zmiany nazwy interfejsu bym nie chciał robić).

Jeżeli coś źle zrozumiałem, to poproszę dodatkowe wyjaśnienia.

**Comment by andrzejkupczyk** [comment]
Okej, wszystko jasne. Dzięki bardzo za wyjaśnienie i podzielenie się planami związanymi z kierunkiem rozwoju paczki. W tej sytuacji muszę szukać dalej lub skroić coś własnego. Nie ma tego zbyt wiele, więc Twoja paczka ma spory potencjał :+1:
