### ISSUE TITLE
Model trait omitting enabled setting

### ISSUE THREAD

**Issue by EntonoX** [prwnr/laravel-streamer#38]
The EmitStreamerEvents trait is omitting the enabled config setting. So if we want to disable emitting streamer events by setting the environment variabel 'REDIS_STREAM_ENABLED' to false, the trait is still emitting events.

Possible solution: add check on config setting in trait

**Comment by prwnr** [comment]
could you elaborate more here? cause I dont remember nor see a `REDIS_STREAM_ENABLED` in my package and I dont recall having an enable/disable feature for emitting the events.

**Comment by EntonoX** [comment]
Ah sorry, my bad. I added a setting inside the config file called 'REDIS_STREAM_ENABLED' myself 😅. 

Because this application is running in various environments i wanted to have controle when redis streams are used and when not. So in my models the 'EmitsStreamerEvents' trait is always declared but i do not want it to fire event according the setting.

**Comment by prwnr** [comment]
ok, now I get it. 
I will try to provide good way of achieving what you need when I will find some free time. hopefully soon. 
most likely I will approach this more on a per-model flag, so it will be a bit more flexible, but still available to be adjusted on your side and made to work for all models. will keep you posted

**Comment by EntonoX** [comment]
Thanks! would be great 😀

**Comment by prwnr** [comment]
@EntonoX check out opened PR if that will suit your needs (also please let me know whether you are using 3.0 version or 2.x and I should also make this change in the previous version)

**Comment by EntonoX** [comment]
@prwnr im currently using the 2.6 tag, but can easily upgrade to 3.x version. The feature is looking good if we want fine grained control so that's nice. But if I simply want to disable all event emitting I think a more global setting would be nice as well. (Otherwise you would need logic in all models and that's seems like unneeded redundancy). Then we have best of both worlds (fine grained and global control).

Very happy you could work on this feature right away 😃

**Comment by prwnr** [comment]
@EntonoX that's why I wrote in the PR, that it can be either on per-model basis or can be done on a base model to apply same logic to all models. this way it is "you" who decides whether its global or not, not me (or Im not leaving two different ways to deal with same thing)

**Comment by EntonoX** [comment]
@prwnr you've got a point there. I skipped directly to the code in the commit and skipped the commit description 😅. Seems like a good solution. A base model is easy to use and obvious.

I think this will fix my issue and is a good addition!

**Comment by prwnr** [comment]
@EntonoX released as 3.1.0 but I will also add this to 2.x branch as 2.7.0 if you will want to stay on it
