### ISSUE TITLE
XReadGroup can't listen event from other languange, even from redis-cli

### ISSUE THREAD

**Issue by dhymasriyanto** [prwnr/laravel-streamer#44]
So, I'm building a microservice app, then I use Laravel Streamer for my service's data transfer communication. Each service use different programming languange, such as PHP (Laravel), JavaScript (ExpressJS), Java (SpringBoot). When I try to listen data for same framework (in this case using Laravel with Laravel Streamer), the listener works. But when I try to publish a message from other service (JavaScript), the listener doesn't work. So I try to figure out with publish the data from redis-cli, but it's still same. Even the group name, and the stream name is correct. Is there a special way to use it? Cause I am new at this.

![2022-06-14 18-55-54](https://user-images.githubusercontent.com/32106219/173572348-a36584ba-f039-422e-950e-e05e52858ee5.gif)

**Comment by prwnr** [comment]
@dhymasriyanto hello.
as far as I remember, when you are listening with group and consumer, having same group - but different consumer - won't get the message to both consumers. The first consumer in the group gets the message, the other consumers are there waiting for another message in case the first one is still busy -> this is Redis Streams behavior: https://redis.io/commands/xreadgroup/#consumer-groups-in-30-seconds

it would be best if you could test this out with different groups and see if the outcome changes. 

the other thing to consider is that this package follows its own format of a message and it wont process message that wont match that format (it expects the Stream message to have at least `data` field in it

**Comment by dhymasriyanto** [comment]
Okay, thanks in advance, but sorry I know that if we listen with groups and consumers, having the same group, with different consumers won't get the message for both. So, in that GIF, I'm trying to send it twice, the first message will be listened to by the JavaScript listener, and the second one is supposed to be listened to by Laravel Stream. 

This GIF below, I'm trying to send it from JS, which will send message (with the `data` field) three times (using looping) into two JS listener and one Laravel Stream listener, but the Laravel listener did not respond anything.

![2022-06-14 19-40-46](https://user-images.githubusercontent.com/32106219/173579673-057140be-7aa5-48d4-82cb-f511e0dd98a9.gif)

And GIF below I'm try to send from Laravel Event, which are all listener works.


![2022-06-14 19-43-15](https://user-images.githubusercontent.com/32106219/173580220-3dbb81a0-8c54-4d84-a84a-39dc6e851c5c.gif)

**Comment by dhymasriyanto** [comment]
> it would be best if you could test this out with different groups and see if the outcome changes.

I try to test with different group, but laravel listener still not respond anything

**Comment by dhymasriyanto** [comment]
Ah... I see. :D Thank you so much!!! Finally, I figure it out how it works.

> while it should be:
> 
> ```
> XADD item.restock * data '{"foo":"bar"}'
> ```
> 
> The main content of the Stream should be inside "data" key.

![image](https://user-images.githubusercontent.com/32106219/173612322-e7c2ca45-8bd9-4de1-809a-9c27b5a6880c.png)

![2022-06-14-22-11-35](https://user-images.githubusercontent.com/32106219/173613293-e10e5f5c-86a9-4063-8f90-fb5462fe7f18.gif)

And I just realized if there is a log there :D

![image](https://user-images.githubusercontent.com/32106219/173611761-94e1ab1b-55e6-4218-b112-1efc6a7af2d8.png)


![image](https://user-images.githubusercontent.com/32106219/173611779-209d367e-8362-4f84-bc32-e05b67877892.png)
