### ISSUE TITLE
Inconsistent exception classes in ListenCommand leading to a fatal error

### ISSUE THREAD

**Issue by yuriy-sorokin** [prwnr/laravel-streamer#56]
Hi,

here it catches \Throwable
https://github.com/prwnr/laravel-streamer/blob/3.5.0/src/Commands/ListenCommand.php#L103

and passes it here
https://github.com/prwnr/laravel-streamer/blob/3.5.0/src/Commands/ListenCommand.php#L271
which expects \Exception in its method signature.

PHP \Error implements \Throwable but does not extend \Exception, so if a handler throws \Error, we'll get the following:

`Prwnr\Streamer\Commands\ListenCommand::printError(): Argument #3 ($e) must be of type Exception, Error given, called in /var/www/html/vendor/prwnr/laravel-streamer/src/Commands/ListenCommand.php on line 107
`

**Comment by yuriy-sorokin** [comment]
PR https://github.com/prwnr/laravel-streamer/pull/57

**Comment by prwnr** [comment]
@yuriy-sorokin good catch, thanks! will merge PR and tag version soon
