### ISSUE TITLE
Laravel 11 Support

### ISSUE THREAD

**Issue by michaelLoeffelmann** [prwnr/laravel-streamer#58]
Hi, 

what are the plans to bring support for laravel 11? Is there a schedule for that?

**Comment by michaelLoeffelmann** [comment]
@prwnr thanks for the quick reply.

**Comment by prwnr** [comment]
@michaelLoeffelmann https://github.com/prwnr/laravel-streamer/releases/tag/4.0.0 released version with Laravel 11 compatibility, a major one however, as Im dropping the old versions, as well as PHP old versions and introducing strict typing to whole package.
